// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWH5tfHcW_njTVsparZp_wc882lUZcao',
    appId: '1:1007787656296:web:06d7ccea40726cad6b67dd',
    messagingSenderId: '1007787656296',
    projectId: 'booking-app-6d26d',
    authDomain: 'booking-app-6d26d.firebaseapp.com',
    storageBucket: 'booking-app-6d26d.firebasestorage.app',
    measurementId: 'G-HV5W96ZG11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnR0PntnF3WtXhvwtEuftB_p5r-67vKo',
    appId: '1:1007787656296:android:42d3c767d830cb6c6b67dd',
    messagingSenderId: '1007787656296',
    projectId: 'booking-app-6d26d',
    storageBucket: 'booking-app-6d26d.firebasestorage.app',
  );
}
